# Generated by Django 3.2.3 on 2021-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBicycle',
            fields=[
                ('bicycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('bicycle_name', models.CharField(max_length=1000)),
                ('bicycle_brand', models.CharField(max_length=1000)),
                ('bicycle_cost', models.IntegerField()),
                ('bicycle_stock', models.IntegerField(default=10)),
                ('bicycle_location', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'addbicycle_table',
            },
        ),
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=1000)),
                ('book_author', models.CharField(max_length=1000)),
                ('book_edition', models.IntegerField()),
                ('book_cost', models.IntegerField()),
                ('book_stock', models.IntegerField(default=10)),
                ('book_location', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'addbook_table',
            },
        ),
    ]
