# Generated by Django 3.2.3 on 2021-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=1000)),
                ('manager_dob', models.CharField(default='00/00/0000', max_length=10)),
                ('manager_email', models.CharField(max_length=1000)),
                ('manager_password', models.CharField(max_length=10)),
                ('manager_age', models.IntegerField()),
                ('manager_mobno', models.CharField(max_length=10)),
                ('manager_address', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'addmanager_table',
            },
        ),
    ]
