# Generated by Django 3.2.3 on 2021-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockadmin', '0002_addmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_model', models.CharField(max_length=1000)),
                ('bike_mil', models.IntegerField()),
                ('bike_cost', models.IntegerField()),
                ('bike_stock', models.IntegerField(default=10)),
                ('bike_location', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'addbike_table',
            },
        ),
    ]
