# Generated by Django 3.2.3 on 2021-05-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockadmin', '0003_addbike'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbike',
            name='bike_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
