# Generated by Django 3.2.3 on 2021-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=1000)),
                ('bcname', models.CharField(max_length=1000)),
                ('bccost', models.IntegerField()),
                ('bicycle_category', models.CharField(choices=[('sports', 'sports'), ('road', 'road'), ('Others', 'Others')], max_length=50)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('mob', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=10000)),
                ('staff_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bicycleorders_table',
            },
        ),
    ]
