# Generated by Django 3.2.3 on 2021-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=1000)),
                ('staff_dob', models.CharField(default='00/00/0000', max_length=10)),
                ('staff_email', models.CharField(max_length=1000)),
                ('staff_password', models.CharField(max_length=10)),
                ('staff_age', models.IntegerField()),
                ('staff_mobno', models.CharField(max_length=10)),
                ('staff_address', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'addstaff_table',
            },
        ),
    ]
